# Build the project
build:
    uv sync

# Run tests
test: build
    uv run --frozen pytest

check:
    uv run ruff check

fix:
    uv run ruff check --fix

fix-all:
    uv run ruff check --fix --unsafe-fixes

run:
    uv run mcp-google-api-server

tunnel:
    cloudflared tunnel --url http://localhost:7878