schema_version = "1"

[project]
name = "mcp-server-python-mcp"
kind = "mcp-server"

[zone]
url = "https://lmnhzl0cq4ursfuqddt37fcehw.keycard.cloud"

[server]
command = "uv run uvicorn main:app --port 8000"
port = 8000
